name: github_search_flutter_client_rxdart_example
description: A GitHub search flutter client RxDart example.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  provider:
  freezed_annotation: ^0.12.0 
  json_annotation: ^3.1.1
  http: ^0.12.2
  rxdart: ^0.25.0
  font_awesome_flutter: ^8.11.0 
  cupertino_icons: ^1.0.0
  flutter_staggered_grid_view: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  build_runner: ^1.11.0
  
flutter:
  uses-material-design: true